### PR TITLE
v2? 

### PR DESCRIPTION
**Pull request by bmclare19**
## Overview
My initial goal was to change the energy ticker from throttling updates by 5 to instead smooth updates every time energy was gained. One thing lead to another and this is where we are a week later. I saw a lot of commented out code and other room for improvement so I just started working on it. If you don't want to bother looking at this, that's fine but I'm making it generally available to anyone that might want it. 

This works for all versions of the WoW. 

All packaging steps and github workflows were updated to work properly with the new code base.

## How to use
Copy the contents of the release to `Interface/Addons/NugEnergy`. Configuration settings did change but nothing should conflict. 

## Organization
- Re-organized project file structure
- Created logical groups using folders and moved files accordingly
- Separated out code from `NugEnergy.lua` into files with focused scope
- Updated and organized all toc files imports 

## Libraries
- Added new libraries to facilitate development

### New Libraries:
- AceAddon-3.0 - Primary entry point for NugEnergy.
- AceDBOptions-3.0 - Manages adding/updating/removing addon profiles
- AceEvent-3.0 - Event management of the whole addon
- AceLocale-3.0 - Manages locales. Primary use case is in interface options

## Locales
- Added 7 new locales
- Added `locales.xml` to manage locale imports in one location
- Updated locale manager object to use AceLocale-3.0
- Updated locale object to include an entry for every public string that needs to be localized (for all existing and new locales as well)
- Created script to generate locales on the fly (uses Google Translate so results may need minor updates)

### New Locales:
- German - Germany (de-de)
- Spanish - Spain (es-es)
- Spanish - Mexico (es-mx)
- French - France (fr-fr)
- Italian - Italy (it-it)
- Korean - Korea (ko-kr)
- Portuguese - Brazil (pt-br)

## Media
- Separated out media elements into their own folders
- Added new fonts
- Added font licenses 

### New Fonts:
- OpenSans-Light
- OpenSans-Medium
- OpenSans-Regular
- Gidole-Regular

### NugEnergy (global)
 `NugEnergy` object now manages the addon scope instead of managing addon scope and also being the primary frame. This changes the design to where `NugEnergy` is the controller of the addon in what is a more traditional (but not strict) MVC. A new `statusBar` element is created and set as a child of `NugEnergy` to provide access to handling UI updates. Object creation was simplified to use `AceAddon` via `LibStub("AceAddon-3.0"):NewAddon("NugEnergy", ...mixins)`.

#### Scope
- Lifecycle: Initialization, Enabled, Disabled
- Orchestrating UI updates
- State management
- Events
- Settings
- Profiles

#### Visual State 
The visual state of the addon is manage by calls to `NugEnergy:UpdateVisibility()`. This call checks the current state and first checks if the state has changed before doing anything. If the state is unchanged then it silently returns without doing anything. This design decision is an important one because it asserts that nothing should happen without a state change, as would be expected of a functioning state machine. 

The state required to show was also updated to include a few new situations:

    function NugEnergy:ShouldShow()
        return state.wasJustEnabled or state.forceShow or state.isInCombat or state.isStealthed or (not state.isPowerFull)
    end

All state management is handled internal (private scope) by `NugEnergy` but a read-only state is exposed via `NugEnergy.state`. The privately scoped `state` object is mixed with an `observable` so that specific state changes can be watched if needed. This is exposed from the root object via `NugEnergy:OnSttate` and `NugEnergy:OffState`. For more information about the observable mixing look at `core/utils.lua#observable`. 

### NugEnergy Frames
All frames and behaviors are created via `NugEnergy:CreateComponents()` which is only called in the `OnEnable` handler. `CreateComponents` can be called multiple times without issue - it will only ever creates components once.

#### Frames
All frames are created via encapsulated factory functions in `NugEnergy_Frames.lua`. These will be moved from the common frames file to individual files in `core/frames` in future releases. Frame elements manage configuration changes via `self:Update()` which is a custom function that updates all changed configurations, unique to each frame element. Furthermore, all updates to associated elements, such as the status bar texture and the background texture, are managed via hooks like so:
    
    hooksecurefunc(
        statusBar,
        "SetStatusBarTexture",
        function(_, texture)
            if (type(texture) == "table" and texture.GetTextureFilePath) then
                background:SetTexture(texture:GetTextureFilePath())
            else
                background:SetTexture(texture)
            end
        end
    )

This reduces the overhead required to update a linked state and passes that effort over the frames themselves. Using `hooksecurefunc` ensures that you are only ever running a hook *after* the function has finished running on the hooked element and further, hooks cannot modify the value which means you can safely hook as many times as you want. The only drawback is that you can't unhook functions that you've already hooked, so you just need to manage whether or not the function should run when it is called.

Handler objects were created in cases where multiple frames represented the same NugEnergy "component". This includes the `border` and `marks`. 

##### Border Handler
The border handler makes use of the same logic that was previously used but instead of exposing both the `border` and `backdrop` frames to `NugEnergy` everything is managed via calls to `NugEnergy.border`. 

##### Mark Handler
The mark handler controls adding and removing marks from the status bar. It is accessed via `NugEnergy.markHandler`. The new configuration makes the mark handler much more extensible and in future updates marks will be able to be configured with different visual settings as well. Furthermore, the mark handler manages it's own pool of mark frames so that it doesn't unnecessarily create new frames but instead will re-use frames that aren't currently shown. 

#### Behaviors
Behaviors are really "features" or "extensions" of `NugEnergy`. They manage the functionality of the addon based on different factors. Given the reliance on events, behaviors are modeled as frames, but they aren't visual elements. In the future all behaviors will be moved to `core/behaviors`. 

##### Power Level Colors (PLC)
PLC manages the color of the status bar based on current power levels. Thresholds are all percentage based instead of actual values because this makes it easier to configure for multiple scenarios (e.g. raid buffed you have more mana, etc.). Only low and high colors are needed because if the current power level isn't low or high the default bar color is used. Low thresholds override high thresholds (because low is checked first), so in the event the high threshold is lower than the low threshold, the low color will be used until it passes the low threshold and then the high color will be used. This functionality is purposeful, as a means to override the bar color at any time.

##### Fader
The bar fader updates the transparency of the bar and text (as configured) after the bar is no longer needed to show. Configurations were added for delay (time in secs after no longer needing to show to start fading) and duration (time in secs to fade). 

##### Spender Feedback
The texture that shows all expenditures of power and then fades out. New configuration settings were added to modify this behavior.

##### Alerts
The frame that handles showing the alert animation. Currently doesn't do anything but will be extended significantly in future updates. 

#### NugEnergy Ticker
The ticker is currently unchanged and also unused because I haven't bother to log into SOM and work with it. Will be updated in the future. 

### NugEnergy Config
The configuration management was ultimately redundant. Instead of having configurations manage settings, this was removed in favor of AceDBOptions, which is the profile management used by most addons (Plater, ElvUI, WA, etc.). Further, event management was generally common, so that was all abstracted out to the root `NugEnergy` object where it can be enhanced/changed via `behaviors`. All power changes are now handled intrinsically using events. This also leaves room to handle "power specific" settings which has been requested before. 

Most of the same functionality is supported, however some was removed given I didn't understand it's purpose. `FSR` is an example of this. I'll be happy to add it back in when I know what it should do.

### NugEnergy Settings
Interface options were changed and re-structured. All fields that need localization were added to do so. The interface options layout was redone to help organize like settings. Given the new well defined structure, updates to the addon DB are simplified to a single common entry point.

    local _get = function(transformer)
        transformer = transformer or function(t)
                 return t
             end
         return function(info)
             local temp = NugEnergy.db.profile
             for _, v in ipairs(info) do
                 local match = string.match(v, "^noarg_")
                 if (match == nil) then
                     temp = temp[v]
                 end
             end
             return transformer(temp)
         end
     end

     local _set = function(transformer, onupdate)
         transformer = transformer or function(...)
                 return ...
             end
         return function(info, ...)
             local temp = NugEnergy.db.profile
             for i = 1, #info - 1 do
                 local v = info[i]
                 local match = string.match(v, "^noarg_")
                 if (match == nil) then
                     temp = temp[v]
                 end
             end
             temp[info[#info]] = transformer(...)
             if (onupdate) then
                 onupdate()
             end
         end
     end

All child elements of the group property `args` should map to a DB path at the same depth. In some situations this doesn't work because you might want to group some options in the interface panel but not in the DB configuration itself. To handle this just prefix the arg with `noarg_` and the getter/setter will silently ignore it. As long as updates to the `SETTINGS_CONFIG` object follow the same pattern then no additional work is needed to get or set configurations. 

#### Custom get/set
There are a few notable exceptions to this common format such as colors, which are stored as a table but expected as multiple return values from getters and as multiple values for setters. In the event you need to handle this, you can pass in a `transformer` that transforms the incoming or outgoing data to fit the expectation.

    get = _get(unpack),
    set = _set(
        function(r, g, b, a)
            return {r, g, b, a}
        end
    )

As can be seen, the getter is created with a transformer of `unpack` which will return separated elements of a color table (array) which handles the expectation of AceConfigDialog-3.0. And for the set function, a custom function is passed in that transforms the separated r g b a elements to a array like the DB expects. 

#### Handling Updates
The  `_set` functions also provide an arg for an `onupdate` function which will be called upon successful execution of the set function. This can be added in addition to the `transformer` arg if needed like so:

    set = _set(
        function(r, g, b, a)
            return {r, g, b, a}
        end,
        function()
            NugEnergy.statusBar:Update()
        end
    )

Or without a `transformer` arg like so:

    set = _set(
        nil,
        function()
            NugEnergy.statusBar:Update()
        end
    )

#### Appearance
Manages all visual settings for the status bar frame and the text frame. More options were added over the previous implementation to give a higher degree of control. 

#### Behaviors
Manages `NugEnergy` features such as power level coloring, fader, spender feedback, alerts, and execute. All behaviors can be enabled or disabled at any time. The addon will handle updating the state to ensure proper functionality regardless of which features are enabled or not. Additional options were added to give more control over how the addon behaves.

#### Profiles
Manages all Profiles for the addon. Users can select which profile they want to use and those settings will be applied to the addon.

### NugEnergy Defaults
All default settings were broken out of the main file into their own file in `core/defaults.lua`. The defaults must be organized the same way as the interface options configuration.

### CODE REVIEW

**Comment by d87** [comment]
I appreciate the passion, but that's a no.

**Comment by bmclare19** [comment]
Anything in particular you don't like?

**Comment by d87** [comment]
Well for one you don't just barge in to refactor people's code based on your own subjective ideas of beauty. Secondly, not of this size.

I know AceAddon and AceLocale exist and using them doesn't make anything suddenly better or any different even.

I'm of the opinion that out of context machine translations are worse than no translation at all. With Chinese translations already present, other countries usually have at least some familiarity with basic level english.

Changing settings format resets existing user settings. And at the end of the day it's an addon for single progress bar, for people who want rocket ship settings to the point of selecting drawlayer of textures and vertical text alignment there's WeakAuras.
Also I don't share the opinion that having a single _obscure_ setter funcion is more simple than explicit setters and getters for each field. Not only you still need to, but now you must mirror the database with your GUI.

Nitpick, but hooksecurefunc is for hooking secure functions, not a "proper way to do hooks".

I stopped using manual changelog before, no one gives a shit about addon changes, and those who do will get what they want usually from auto changelog.

Maybe the main file needs some code splitting, but it's still decently sectioned and 2k lines all in all, so that's not a huge problem.

You may not like it, but it's simple and it works. And I'm currently hands off with my addons because I can't actually play, and the last thing I need is someone scrambling one of them for basically no reason.

**Comment by bmclare19** [comment]
> And I'm currently hands off with my addons because I can't actually play, and the last thing I need is someone scrambling one of them for basically no reason.

Ahh, I didn't realize you were more hands off these days. That makes much more sense. My intention wasn't to get you all upset or defensive. Good luck in your future development!

**Pull request closed without merging**
